### ISSUE TITLE
Container: ModuleNotFoundError: No module named 'views_applications'

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-portal#128]
## Error

For the `release-stage` of the `./resources/docker/Dockerfile` the following error is present:
```shell
/python3/venv/lib/python3.6/site-packages/jwt/utils.py:8: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.primitives.asymmetric.utils import (
Traceback (most recent call last):
  File "/slate/run_portal.py", line 3, in <module>
    from portal import app
  File "/slate/portal/__init__.py", line 70, in <module>
    import portal.views
  File "/slate/portal/views.py", line 27, in <module>
    import views_applications
ModuleNotFoundError: No module named 'views_applications'
```

## Steps to reproduce

Build the image.
```shell
docker build --file ./resources/docker/Dockerfile --target release-stage --tag bob:local .
```
Run the container where the `portal.conf` file is created in the usual way for local development (see the docs in this repo).
```shell
docker run -it -v ${PWD}/instance/portal.conf:/slate/instance/portal.conf  bob:local
```

**Comment by adamhgriffith-uofu** [comment]
So interestingly the `release-stage` needs the `yum` packages `libffi-devel` and `python3-devel` or else we get the following spew while building the image:
```shell
Building wheel for misaka (setup.py): started
  Building wheel for misaka (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /python3/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ptqg845y/misaka_86479a3ccab346f1889525695dba00be/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ptqg845y/misaka_86479a3ccab346f1889525695dba00be/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-hhr8h3o4
       cwd: /tmp/pip-install-ptqg845y/misaka_86479a3ccab346f1889525695dba00be/
  Complete output (27 lines):
  /python3/venv/lib/python3.6/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
    SetuptoolsDeprecationWarning,
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/misaka
  copying misaka/utils.py -> build/lib.linux-x86_64-3.6/misaka
  copying misaka/callbacks.py -> build/lib.linux-x86_64-3.6/misaka
  copying misaka/api.py -> build/lib.linux-x86_64-3.6/misaka
  copying misaka/__init__.py -> build/lib.linux-x86_64-3.6/misaka
  copying misaka/constants.py -> build/lib.linux-x86_64-3.6/misaka
  running build_ext
  generating cffi module 'build/temp.linux-x86_64-3.6/misaka._hoedown.c'
  creating build/temp.linux-x86_64-3.6
  building 'misaka._hoedown' extension
  creating build/temp.linux-x86_64-3.6/build
  creating build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/misaka
  creating build/temp.linux-x86_64-3.6/misaka/hoedown
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Imisaka -I/python3/venv/include -I/usr/include/python3.6m -c build/temp.linux-x86_64-3.6/misaka._hoedown.c -o build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/misaka._hoedown.o
  build/temp.linux-x86_64-3.6/misaka._hoedown.c:50:26: fatal error: pyconfig.h: No such file or directory
   #    include <pyconfig.h>
                            ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for misaka
  Running setup.py clean for misaka
Successfully built Flask-Markdown
Failed to build misaka
Installing collected packages: zipp, typing-extensions, pycparser, MarkupSafe, importlib-metadata, dataclasses, cffi, Werkzeug, urllib3, pyjwt, Jinja2, itsdangerous, idna, cryptography, click, charset-normalizer, certifi, WTForms, requests, misaka, markdown, geographiclib, Flask, pygal, globus-sdk, geopy, Flask-WTF, Flask-Misaka, Flask-Markdown
    Running setup.py install for misaka: started
    Running setup.py install for misaka: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /python3/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ptqg845y/misaka_86479a3ccab346f1889525695dba00be/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ptqg845y/misaka_86479a3ccab346f1889525695dba00be/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-tz9hz2_t/install-record.txt --single-version-externally-managed --compile --install-headers /python3/venv/include/site/python3.6/misaka
         cwd: /tmp/pip-install-ptqg845y/misaka_86479a3ccab346f1889525695dba00be/
    Complete output (27 lines):
    running install
    /python3/venv/lib/python3.6/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/misaka
    copying misaka/utils.py -> build/lib.linux-x86_64-3.6/misaka
    copying misaka/callbacks.py -> build/lib.linux-x86_64-3.6/misaka
    copying misaka/api.py -> build/lib.linux-x86_64-3.6/misaka
    copying misaka/__init__.py -> build/lib.linux-x86_64-3.6/misaka
    copying misaka/constants.py -> build/lib.linux-x86_64-3.6/misaka
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-3.6/misaka._hoedown.c'
    creating build/temp.linux-x86_64-3.6
    building 'misaka._hoedown' extension
    creating build/temp.linux-x86_64-3.6/build
    creating build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/misaka
    creating build/temp.linux-x86_64-3.6/misaka/hoedown
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Imisaka -I/python3/venv/include -I/usr/include/python3.6m -c build/temp.linux-x86_64-3.6/misaka._hoedown.c -o build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/misaka._hoedown.o
    build/temp.linux-x86_64-3.6/misaka._hoedown.c:50:26: fatal error: pyconfig.h: No such file or directory
     #    include <pyconfig.h>
                              ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /python3/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ptqg845y/misaka_86479a3ccab346f1889525695dba00be/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ptqg845y/misaka_86479a3ccab346f1889525695dba00be/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-tz9hz2_t/install-record.txt --single-version-externally-managed --compile --install-headers /python3/venv/include/site/python3.6/misaka Check the logs for full command output.
```

**Comment by adamhgriffith-uofu** [comment]
Ok. Have things working on the feature branch (see on right). Something to note is that the version of Python3 on Centos7 is no longer supported.
```shell
$ docker run -it -v ${PWD}/instance/portal.conf:/slate/instance/portal.conf  bob:local 
/python3/venv/lib/python3.6/site-packages/jwt/utils.py:8: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.primitives.asymmetric.utils import (
 * Serving Flask app 'portal' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.2:5050/ (Press CTRL+C to quit)
 * Restarting with stat
/python3/venv/lib/python3.6/site-packages/jwt/utils.py:8: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.primitives.asymmetric.utils import (
 * Debugger is active!
 * Debugger PIN: 606-973-812
```
